#pragma once
#include <unordered_map>
#include <string>
#include <iostream>
#include <filesystem>
#include <SFML/Graphics.hpp>
#include "StructureDefinition.h"
#include "core/SpritesheetManager.h"
#include "core/GameConfig.h"

namespace RPG {


    struct AssetDefinition {
        std::string name;
        uint32_t x, y, w, h;          // Position at atlas.png
        uint32_t hb_w, hb_h;          // Hitbox dimensions
        uint32_t off_x, off_y;        // Hitbox offset relative point (x,y)
        bool blocks;             
        StructureType type;      
    };

    struct AssetTemplate {
        StructureType type;
        StructureMetadata meta;
        PlacementLayer layer;
    };


    /**
     * @brief Centralized manager for game assets.
     *
     * AssetManager handles both:
     * 1. Structure definitions (`structureLibrary`)
     * 2. Spritesheets, textures, and fonts
     *
     * It ensures resources are loaded only once and provides
     * easy access via string identifiers or structure types.
     */
    class AssetManager {
    private:

        // ==============================
        // Singleton Core
        // ==============================
        // Private constructor
        AssetManager() = default;

        // ==============================
        // Structure Definitions, mapping rules
        // ==============================
        std::unordered_map<std::string, StructureDefinition> structureLibrary;
        std::unordered_map<std::string, AssetTemplate> prefixes;
        std::unordered_map<int, std::string> idToNameMap;

        // ==============================
        // Spritesheets, Textures, Fonts
        // ==============================
        std::unordered_map<std::string, Spritesheet> spritesheetMap;
        std::unordered_map<std::string, sf::Texture> textureMap;
        std::unordered_map<std::string, sf::Font> fontMap;

    public:
        // ==============================
        // Singleton Access
        // ==============================

        /**
         * @brief Gets the global Singleton instance of the AssetManager.
         */
        static AssetManager& getInstance();

        // Delete copy constructor and assignment operator to enforce Singleton
        AssetManager(const AssetManager&) = delete;
        AssetManager& operator=(const AssetManager&) = delete;

        // Delete move semantics
        AssetManager(AssetManager&&) = delete;
        AssetManager& operator=(AssetManager&&) = delete;

        // ==============================
        // Structure Management
        // ==============================

        /**
         * @brief Initializes structure definitions and registers necessary textures.
         * @param sm Reference to a SpritesheetManager for registering textures.
         *
         * This function populates `structureLibrary` with default terrain,
         * obstacles, and special zones, and loads required textures into
         * the spritesheet manager.
         */
        void init();

        /**
         * @brief Loads and parses the manifest JSON file generated by the Python script.
         * @param path The relative path to the manifest file (e.g., tile_ids.json).
         * * Iterates through the JSON definitions, matches them with existing prefix rules,
         * and populates the `structureLibrary` with pixel-perfect hitboxes and texture coordinates.
         */
        void loadManifest(const std::string& path, const std::string& textureKey);


        void loadTemplates(const std::string& path);


        PlacementLayer stringToLayer(const std::string& str);


        StructureType stringToType(const std::string& str);

        /**
         * @brief Resolves a numeric Asset ID from the manifest back to its string name.
         * @param id The ID found in manifest.json or Tiled GID.
         * @return std::string The name of the asset, or empty string if not found.
         */
        std::string getNameById(const uint32_t& id) const;

        /**
         * @brief Retrieves the definition for a specific structure type.
         * @param type The structure type to query.
         * @return const StructureDefinition& Reference to the structure definition.
         *
         * If the type is not found, it returns the definition for `StructureType::None`.
         */
        const StructureDefinition& getDefinition(const std::string& name) const;
        StructureDefinition& getDefinition(const std::string& name);
        bool hasDefinition(const std::string& name) const;

        // ==============================
        // Spritesheets
        // ==============================

        /**
         * @brief Loads a spritesheet from file and stores it under a unique name.
         * @param name The unique identifier for the spritesheet.
         * @param filepath Path to the image file.
         *
         * Prints an error if the name already exists or if loading fails.
         */
        void addSpritesheet(const std::string& name, const std::string& filepath);

        /**
         * @brief Retrieves a pointer to a stored spritesheet.
         * @param name The unique identifier used when adding the spritesheet.
         * @return const Spritesheet* Pointer to the spritesheet, or nullptr if not found.
         */
        const Spritesheet* getSpritesheet(const std::string& name) const;
        const Spritesheet& getTest(const std::string& name) const;

        // ==============================
        // Textures
        // ==============================

        /**
         * @brief Loads an sf::Texture from file and stores it under a unique name.
         * @param name The unique identifier for the texture.
         * @param filepath Path to the image file.
         *
         * Useful for standalone images not part of a spritesheet (backgrounds, UI).
         */
        void addTexture(const std::string& name, const std::string& filepath);

        /**
         * @brief Retrieves a pointer to a stored sf::Texture.
         * @param name The unique identifier used when adding the texture.
         * @return const sf::Texture* Pointer to the texture, or nullptr if not found.
         */
        const sf::Texture* getTexture(const std::string& name) const;

        std::string getDefinitionByType(const StructureType& type) const;

        // ==============================
        // Fonts
        // ==============================

        /**
         * @brief Loads an sf::Font from file and stores it under a unique name.
         * @param name The unique identifier for the font.
         * @param filepath Path to the font file (e.g., .ttf).
         */
        void addFont(const std::string& name, const std::string& filepath);

        /**
         * @brief Retrieves a pointer to a stored sf::Font.
         * @param name The unique identifier used when adding the font.
         * @return const sf::Font* Pointer to the font, or nullptr if not found.
         */
        const sf::Font* getFont(const std::string& name) const;
    };

}
